### ISSUE TITLE
suggestion about attributes

### ISSUE THREAD

**Issue by kostya** [spider-gazelle/pg-orm#2]
why not used instance variables like in json serializable?

```
class Foo
  include Model

  property name : String
  property foo : Hash(String, String)
 ......
end
```

it allows also add json serializable or any other.

**Comment by kostya** [comment]
It is still limited, why if want to add msgpack serializable. Why you need to hack `property` macro, if there is annotations? It is suggestion, in my opinion, using module and annotations give much more flexibity.

**Comment by kostya** [comment]
Because if you have properties you can add custom extensions, whatever you want, just live Serializable modules. But with attribute, i dont know how it implemented internally, so i cant do it easily, may be it also use instance variables. Extensions like: msgpack generator, documentation generator, api generator (rpc,web).

**Comment by np-nam** [comment]
@kostya you can still use your annotations for the instance variables as you like, just put it before the `attribute` call.

As you can see from this file: https://github.com/spider-gazelle/active-model/blob/master/src/active-model/model.cr#L702
the attribute macro directly generate the variable declaration instead of push it to a temporal array and generate later (like Clear ORM).

**Comment by kostya** [comment]
ok, thanks
